conf_layout:
  lconfig_altChooser:
    tag: AltChooserBoundedSearch
    contents: 3
  lconfig_importColumn: 50
  lconfig_hangingTypeSignature: true
  lconfig_alignmentLimit: 30
  lconfig_indentListSpecial: true
  lconfig_indentAmount: 2
  lconfig_alignmentBreakOnMultiline: true
  lconfig_cols: 160
  lconfig_indentPolicy: IndentPolicyFree
  # lconfig_indentPolicy: IndentPolicyMultiple
  lconfig_indentWhereSpecial: true

  lconfig_columnAlignMode:
    tag: ColumnAlignModeMajority
    contents: 0.7
